[package]
name = "digital_test_to_verilog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
digital_test_runner = { path = "../digital_test_runner" }
