/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// 4-bit arithmetic logic unit
module \74181  (
  input Cn,
  input \~A0 ,
  input \~A1 ,
  input \~A2 ,
  input \~A3 ,
  input \~B0 ,
  input \~B1 ,
  input \~B2 ,
  input \~B3 ,
  input S0,
  input S1,
  input S2,
  input S3,
  input M,
  input VCC,
  input GND,
  output \~G ,
  output \~P ,
  output \~F0 ,
  output \~F1 ,
  output \~F2 ,
  output \~F3 ,
  output \A=B ,
  output \Cn+4 
);
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire \~F0_temp ;
  wire \~F1_temp ;
  wire \~F2_temp ;
  wire \~G_temp ;
  wire \~F3_temp ;
  assign s4 = ~ \~B0 ;
  assign s7 = ~ \~B1 ;
  assign s10 = ~ \~B2 ;
  assign s13 = ~ \~B3 ;
  assign s16 = ~ M;
  assign s5 = ~ ((s4 & S1) | (S0 & \~B0 ) | \~A0 );
  assign s6 = ~ ((S3 & \~B0  & \~A0 ) | (\~A0  & S2 & s4));
  assign s8 = ~ ((s7 & S1) | (S0 & \~B1 ) | \~A1 );
  assign s9 = ~ ((\~B1  & S3 & \~A1 ) | (\~A1  & S2 & s7));
  assign s11 = ~ ((s10 & S1) | (S0 & \~B2 ) | \~A2 );
  assign s12 = ~ ((\~B2  & S3 & \~A2 ) | (\~A2  & S2 & s10));
  assign s14 = ~ ((s13 & S1) | (S0 & \~B3 ) | \~A3 );
  assign s15 = ~ ((S3 & \~B3  & \~A3 ) | (\~A3  & S2 & s13));
  assign \~F0_temp  = ((s6 & ~ s5) ^ ~ (s16 & Cn));
  assign \~F1_temp  = ((s9 & ~ s8) ^ ~ ((Cn & s6 & s16) | (s5 & s16)));
  assign \~F2_temp  = ((s12 & ~ s11) ^ ~ ((s9 & s6 & Cn & s16) | (s9 & s5 & s16) | (s8 & s16)));
  assign \~F3_temp  = ((s15 & ~ s14) ^ ~ ((s12 & s9 & s6 & Cn & s16) | (s12 & s9 & s5 & s16) | (s12 & s8 & s16) | (s11 & s16)));
  assign \~P  = ~ (s15 & s12 & s9 & s6);
  assign \~G_temp  = ~ (s14 | (s15 & s11) | (s15 & s12 & s8) | (s15 & s12 & s9 & s5));
  assign \A=B  = (\~F3_temp  & \~F2_temp  & \~F1_temp  & \~F0_temp );
  assign \Cn+4  = ~ (\~G_temp  & ~ (s15 & s12 & s9 & s6 & Cn));
  assign \~G  = \~G_temp ;
  assign \~F0  = \~F0_temp ;
  assign \~F1  = \~F1_temp ;
  assign \~F2  = \~F2_temp ;
  assign \~F3  = \~F3_temp ;
endmodule
